<?php

function dwnFG_($path, $url, $ending=""){
	$fg=getLast($url). $ending;
	$filepth=$path;
	$file=$filepth.$fg;
	while(file_exists($file)){
		$file=$filepth.gnrtNewString(3, 4).$fg;
	}
	@mkdir($filepth, 0777, true);
	downloadFile($url, $file);
	return $file;
}

function dwnFG($path, $url, $ending=""){
	$file=$fg=cleanLink($path. $ending);
	// $file=getLast($fg);
	downloadFile($url, $file);
	return $file;
}

function downloadFile($url, $path){ 
	$newfname = $path; 
	$file = fopen($url,'rb');
	if($file){        
		$newf = fopen($newfname,'wb');
		if($newf){
			while(!feof($file)){ 
				fwrite($newf, fread($file,1024*8),1024*8);
			}
		}
	}
	if($file){      
		fclose($file);
	}
	if($newf)
	{      
		fclose($newf);
	}
}

function getLast($vr){
	$arr=explode("\\", $vr);
	$last=count($arr)-1;
	$vr=$arr[$last];
	$arr=explode("/", $vr);
	$last=count($arr)-1;
	return $arr[$last];
}

function GenerateRandomColor($noHash=false){
    $color = (!$noHash)?'#':"";
    $colorHexLighter = array("9","A","B","C","D","E","F" );
    for($x=0; $x < 6; $x++):
        $color .= $colorHexLighter[array_rand($colorHexLighter, 1)]  ;
    endfor;
    return substr($color, 0, 7);
}

function autogenerateDp($user){
	$rel____=getRel____();
	  $array_nose=array("nose2"=>"nose2","nose3"=>"nose3","nose4"=>"nose4","nose5"=>"nose5","nose6"=>"nose6","nose7"=>"nose7","nose8"=>"nose8","nose9"=>"nose9");
	  $array_mouth=array("mouth1"=>"mouth1","mouth3"=>"mouth3","mouth5"=>"mouth5","mouth6"=>"mouth6","mouth7"=>"mouth7","mouth9"=>"mouth9","mouth10"=>"mouth10","mouth11"=>"mouth11");
	  $array_eyes=array("eyes1"=>"eyes1","eyes2"=>"eyes2","eyes3"=>"eyes3","eyes4"=>"eyes4","eyes5"=>"eyes5","eyes6"=>"eyes6","eyes7"=>"eyes7","eyes9"=>"eyes9","eyes10"=>"eyes10");
	  $eyes=array_rand($array_eyes);
      $mouth=array_rand($array_mouth);
      $nose=array_rand($array_nose);
      $color=GenerateRandomColor(true);
      $color;

    $link_to_image_='/avatars/face/'.$eyes.'/'.$nose.'/'.$mouth.'/'.$color;

    $link_to_image="https://api.adorable.io".$link_to_image_;

    $e=gnrtNewString(1, 3);
    $ret=genFileName(gnrtNewString(6, 16).$e);
    $ty=$rel____.IMGSTORE___."/";

    @mkdir($ty, 0777, true);
    $f_location=$ty.$ret;
    $f_location_=$f_location.'.png';
    while(is_file($f_location_) && file_exists($f_location_)){          
      $ret=genFileName(gnrtNewString(6, 16).$e);
      $ty=$rel____.IMGSTORE___."/";
      @mkdir($ty, 0777, true);  
      $f_location=$ty.$ret;
      $f_location_=$f_location.'.png';
    }
    $ppic=getFileName(dwnFG($f_location, $link_to_image, $ending=".png"));
    saveDPToDB($user, $ppic);
    $saveto=$ppic;
    return $ppic;
}

function autogenerateDpFromFile($user, $isgroup=false){
  	if(!AUTO_GEN_DP_AT_START){
  	   return "";
  	}
    
    $store = IMGSTORE___;
    $dppp = getDpFromUsername_($user);
    $saveto =$toy = generateNewDpImgLink($store, $dppp);
    $cc=copy(ROOT_DIR.$dppp, ROOT_DIR.$saveto);

    $savet =$to = generateNewDpImgLink(IMG_STORE, $dppp);
    $cc=copy(ROOT_DIR.$dppp, ROOT_DIR.$savet);
    $time=CURRENT_TIME;

    $text=translate("just_edit_dp");          
    $ret=DEF_URL."/".$to;

    if($isgroup){
      $e="INSERT INTO messages (id, auth, recip, privacy_, time, message, picture, is_uneditable, reply_to, ext_link, is_group) VALUES(NULL, '$user', '$user', ".privacy_public.", $time, '$text', '$ret', 0, 0, 1, 1)";    
    }else{
      $e="INSERT INTO messages (id, auth, recip, privacy_, time, message, picture, is_uneditable, reply_to, ext_link, is_group) VALUES(NULL, '$user', '$user', ".privacy_public.", $time, '$text', '$ret', 0, 0, 1, 0)";
    }        
    queryMysql($e);

    return DEF_URL."/".$toy;
  }
?>